### ISSUE TITLE
Error al tejer

### ISSUE THREAD

**Issue by naui2003** [maestria-geotel-201902/unidad-0-asignacion-99-mi-proyecto-naui2003#1]
Profesor estamos teniendo error al tejer 

![image](https://user-images.githubusercontent.com/39661108/72655333-732f0780-396a-11ea-982b-12afb3e5ffb3.png)

**Comment by geofis** [comment]
La barra vertical que está en `title` debe borrarse:

Está así:

```
title: |Relación de los Centros de Refugios respecto a las viviendas construidas con techo de zinc, la vulnerabilidad ante los fenómenos atmósfericos.
```

Debería estar así:

```
title: Relación de los Centros de Refugios respecto a las viviendas construidas con techo de zinc, la vulnerabilidad ante los fenómenos atmósfericos.
```

En algún momento que me visitaron, les comenté que tenían un objeto inexistente en la línea 144, que había que arreglar. Ese objeto no les va a dejar tejer, así que deberán corregirlo.

**Comment by naui2003** [comment]
Porque nos esta pasando esto en el RMD. 


![image](https://user-images.githubusercontent.com/39661108/72655785-3d3f5280-396d-11ea-9b4a-7ec33a62ca0c.png)

**Comment by geofis** [comment]
La respuesta general es porque tejer no se puede dejar para el último día.

Prueben marcar la opción `Chunk output in console`, para que la opción `Chunk output inline` quede desmarcada. 

Ejecutar en la consola `dev.off()` hasta que dé error.
