### ISSUE TITLE
otro error diferente

### ISSUE THREAD

**Issue by naui2003** [maestria-geotel-201902/unidad-0-asignacion-99-mi-proyecto-naui2003#2]
Ahora aparece otro. 

![image](https://user-images.githubusercontent.com/39661108/72655982-a6739580-396e-11ea-8ef7-fab07edf8930.png)

**Comment by geofis** [comment]
¿Ejecutando en el servidor? Porque lo que dice es que TeX no está instalado, pero el servidor sí lo tiene.
