### ISSUE TITLE
Otro error

### ISSUE THREAD

**Issue by naui2003** [maestria-geotel-201902/unidad-0-asignacion-99-mi-proyecto-naui2003#3]
Ahora nos da este error. Ayudaaaaa
![image](https://user-images.githubusercontent.com/39661108/72656944-619f2d00-3975-11ea-8790-90c11579a007.png)

**Comment by geofis** [comment]
Ya había dicho, en otro *issue*, esto:

>En algún momento que me visitaron, les comenté que tenían un objeto inexistente en la línea 144, que había que arreglar. Ese objeto no les va a dejar tejer, así que deberán corregirlo.

En la visita les dije que ese objeto no existe. Localicen el nombre correcto y corrijan.

**Comment by naui2003** [comment]
Profesor, se mantiene el error , a nuestro entender, en linea 144 trata de LISA MAP, por lo que no entendemos que pasa, si al ejecutar los codigos todo seejecutabien, el problema es al tejer, auxiliooooo, socorrooooo.

**Comment by naui2003** [comment]
mire ahi la linea 144

![image](https://user-images.githubusercontent.com/39661108/72657330-61089580-3979-11ea-8f74-85e0a4080af5.png)

**Comment by geofis** [comment]
Lo que está así...

```
vivref.w.W  <- nb2listw(viv.nb)
vivref.w.W
vivref.w.B <- nb2listw(viv.nb, style = 'B')
vivref.w.B 
```

...está mal, porque debe estar así:

```
vivref.w.W  <- nb2listw(vivref.nb)
vivref.w.W
vivref.w.B <- nb2listw(vivref.nb, style = 'B')
vivref.w.B 
```

Y lo que está así...

```
plot(vivref.nb.k1, coordinates(viv.sp), add=T)
```

....está mal porque debe estar así:

```
plot(vivref.nb.k1, coordinates(vivref.sp), add=T)
```

Los mensajes de error que les están apareciendo están claros: el objeto `viv.nb` no existe, ni `viv.sp`, y por eso no teje. El mensaje de error, el mensaje de error, ahí está la clave.
